#pragma once
// Code generated by the C++ Middleware Writer version 1.14.
#include"ReceiveBuffer.hh"
#include"SendBuffer.hh"
#include"message_ids.hh"
#include<array>
#include<set>
#include<string>
#include<vector>

namespace receive_example_messages{
template <class R>
void Give (::cmw::ReceiveBuffer<R>& buf
         ,::std::vector<int32_t>& az1
         ,::std::string& az2){
  int32_t count[1];
  count[0]=buf.template Give<uint32_t>();
  if(count[0]>0){
    az1.resize(az1.size()+count[0]);
    buf.GiveBlock(&(*(az1.end()-count[0])),count[0]);
  }
  az2=buf.GiveString();
}

template <class R>
void Give (::cmw::ReceiveBuffer<R>& buf
         ,::std::set<int32_t>& az1){
  int32_t count[1];
  count[0]=buf.template Give<uint32_t>();
  auto endIt1=az1.end();
  for(;count[0]>0;--count[0]){
    az1.emplace_hint(endIt1,buf.template Give<uint32_t>());
  }
}

template <class R>
void Give (::cmw::ReceiveBuffer<R>& buf
         ,::std::array<::std::array<float, 2>, 3>& az1){
  buf.GiveBlock(&az1[0][0], sizeof az1 / sizeof(float));
}
}
