#pragma once
// Code generated by the C++ Middleware Writer version 1.14.
#include<SendBuffer.hh>
#include"message_id_types.hh"
#include<array>
#include<plf_colony.h>
#include<set>
#include<string>
#include<vector>

namespace send_messages{
inline void Marshal (::cmw::SendBuffer& buf
         ,message_id_8 const& az1
         ,::std::vector<int32_t> const& az2
         ,::std::string const& az3){
  try{
    buf.ReserveBytes(4);
    buf.Receive(az1);
    buf.ReceiveBlock(az2);
    buf.Receive(az3);
    buf.FillInSize(10000);
  }catch(...){buf.Rollback();throw;}
}

inline void Marshal (::cmw::SendBuffer& buf
         ,message_id_8 const& az1
         ,::std::set<int32_t> const& az2){
  try{
    buf.ReserveBytes(4);
    buf.Receive(az1);
    buf.Receive(static_cast<int32_t>(az2.size()));
    for(auto const& it2:az2){
      buf.Receive(it2);
    }
    buf.FillInSize(10000);
  }catch(...){buf.Rollback();throw;}
}

inline void Marshal (::cmw::SendBuffer& buf
         ,message_id_8 const& az1
         ,::std::array<::std::array<float, 2>, 3> const& az2){
  try{
    buf.ReserveBytes(4);
    buf.Receive(az1);
    buf.Receive(&az2, sizeof az2);
    buf.FillInSize(10000);
  }catch(...){buf.Rollback();throw;}
}

inline void Marshal (::cmw::SendBuffer& buf
         ,message_id_8 const& az1
         ,::plf::colony<::std::string> const& az2){
  try{
    buf.ReserveBytes(4);
    buf.Receive(az1);
    buf.Receive(static_cast<int32_t>(az2.size()));
    for(auto const& it3:az2){
      buf.Receive(it3);
    }
    buf.FillInSize(10000);
  }catch(...){buf.Rollback();throw;}
}
}
