#pragma once
//Code generated by the C++ Middleware Writer version 1.14.
namespace sendMessages{
template<auto id>
void Marshal (::cmw::SendBuffer& buf
         ,::std::vector<int32_t> const& a
         ,::std::string const& b)try{
  buf.ReserveBytes(4);
  buf.Receive(id);
  ReceiveBlock(buf,a);
  Receive(buf,b);
  buf.FillInSize(10000);
}catch(...){buf.Rollback();throw;}

template<auto id>
void Marshal (::cmw::SendBuffer& buf
         ,::std::set<int32_t> const& a)try{
  buf.ReserveBytes(4);
  buf.Receive(id);
  buf.Receive(static_cast<int32_t>(a.size()));
  for(auto const& i1:a){
    buf.Receive(i1);
  }
  buf.FillInSize(10000);
}catch(...){buf.Rollback();throw;}

template<auto id>
inline void Marshal (::cmw::SendBuffer& buf
         ,::std::array<::std::array<float, 2>, 3> const& a)try{
  buf.ReserveBytes(4);
  buf.Receive(id);
  buf.Receive(&a,sizeof a);
  buf.FillInSize(10000);
}catch(...){buf.Rollback();throw;}

template<auto id>
void Marshal (::cmw::SendBuffer& buf
         ,::plf::colony<::std::string> const& a)try{
  buf.ReserveBytes(4);
  buf.Receive(id);
  buf.Receive(static_cast<int32_t>(a.size()));
  for(auto const& i2:a){
    Receive(buf,i2);
  }
  buf.FillInSize(10000);
}catch(...){buf.Rollback();throw;}
}
