os: Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmd: git clean -ffxd

build_script:
  - cmd: call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - cmd: nmake -f makefile.vs MSDEV=vs2017 windows PLATFORM=%PLATFORM% CONFIG=%CONFIGURATION%

