
CC=cl
CFLAGS= -std:c++latest -c -EHsc -O2 -nologo

all: libhome.lib

.c.obj:
	$(CC) $(CFLAGS) -c $*.c -o $*.obj

quicklz.obj: quicklz.h
	$(CC) $(CFLAGS) quicklz.c

marshalling_integer.obj: marshalling_integer.hh
	$(CC) $(CFLAGS) marshalling_integer.cc

SendBuffer.obj: SendBuffer.hh
	$(CC) $(CFLAGS) SendBuffer.cc


objects = quicklz.obj marshalling_integer.obj SendBuffer.obj
libhome.lib: $(objects)
	lib /out:$@ $(objects)

clean:
	del *.obj libhome.lib

install:
	copy *.exe  \Users\Store\bin\
