#pragma once
// Code generated by the C++ Middleware Writer version 1.13.
#include"string_join.hh"
#include"udp_stuff.hh"
#include"SendBuffer.hh"

namespace middle_messages_front{
inline void Marshal (::cmw::SendBuffer& buf
         ,bool az1
         ,int32_t max_length=cmw::udp_packet_max){
  try{
    buf.ReserveBytes(4);
    buf.Receive(az1);
    buf.FillInSize(max_length);
  }catch(...){buf.Rollback();throw;}
}

inline void Marshal (::cmw::SendBuffer& buf
         ,bool az1
         , const char* az2
         ,int32_t max_length=cmw::udp_packet_max){
  try{
    buf.ReserveBytes(4);
    buf.Receive(az1);
    buf.Receive(az2);
    buf.FillInSize(max_length);
  }catch(...){buf.Rollback();throw;}
}

inline void Marshal (::cmw::SendBuffer& buf
         ,bool az1
         ,cmw::string_join const& az2
         ,int32_t max_length=cmw::udp_packet_max){
  try{
    buf.ReserveBytes(4);
    buf.Receive(az1);
    az2.Marshal(buf);
    buf.FillInSize(max_length);
  }catch(...){buf.Rollback();throw;}
}
}
