version: 2
jobs:
  build_gcc_debug:
    machine:
      - image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: apt update && apt install -y cmake ninja-build gcc g++
      - run: cmake -GNinja -H. -B../Debug_build -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build ../Debug_build

  build_gcc_release:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: apt update && apt install -y cmake ninja-build gcc g++
      - run: cmake -GNinja -H. -B../Release_build -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build ../Release_build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_debug
      - build_gcc_release
