
CC=cl
CFLAGS= -std:c++latest -I.. -EHsc -O2 -nologo

all: genz

genz: genz.cc ..\libhome.lib
	del string_join.hh udp_stuff.hh
	$(CC) $(CFLAGS) genz.cc /link ..\libhome.lib  "\program files\Microsoft SDKs\Windows\v7.1\Lib\wsock32.lib"   "\program files\Microsoft SDKs\Windows\v7.1\Lib\ws2_32.lib"

clean:
	del *.obj genz.exe

install:
	copy *.exe  \Users\Store\bin\
