#pragma once
// Code generated by the C++ Middleware Writer version 1.14.
#include"SendBuffer.hh"
#include"string_join.hh"
#include"udp_stuff.hh"
#include"marshalling_integer.hh"

namespace front_messages_middle{
void Marshal (::cmw::SendBuffer& buf
         ,cmw::marshalling_integer const& az1
         , const char* az2
         ,int32_t max_length=cmw::udp_packet_max){
  try{
    buf.ReserveBytes(4);
    az1.Marshal(buf);
    buf.Receive(az2);
    buf.FillInSize(max_length);
  }catch(...){buf.Rollback();throw;}
}
}
