#pragma once
// Code generated by the C++ Middleware Writer version 1.14.
#include<SendBuffer.hh>
#include"udp_stuff.hh"
#include<marshalling_integer.hh>

namespace front_middle{
void Marshal (::cmw::SendBuffer& buf
         ,cmw::marshalling_integer const& az1
         , const char* az2){
  try{
    buf.ReserveBytes(4);
    az1.Marshal(buf);
    buf.Receive(az2);
    buf.FillInSize(cmw::udp_packet_max);
  }catch(...){buf.Rollback();throw;}
}
}
