#pragma once
// Code generated by the C++ Middleware Writer version 1.14.
#include<SendBuffer.hh>
#include"message_id_types.hh"
#include"account_info.hh"
#include<marshalling_integer.hh>
#include<vector>

namespace middle_back{
void Marshal (::cmw::SendBuffer& buf
         ,message_id_8 const& a1
         ,::std::vector<cmw_account> const& a2){
  try{
    buf.ReserveBytes(4);
    buf.Receive(a1);
    buf.ReceiveGroup(a2);
    buf.FillInSize(10000);
  }catch(...){buf.Rollback();throw;}
}

inline void Marshal (::cmw::SendBuffer& buf
         ,message_id_8 const& a1
         ,::cmw::marshalling_integer const& a2
         ,request_generator const& a3){
  try{
    buf.ReserveBytes(4);
    buf.Receive(a1);
    a2.Marshal(buf);
    a3.Marshal(buf);
    buf.FillInSize(700000);
  }catch(...){buf.Rollback();throw;}
}

inline void Marshal (::cmw::SendBuffer& buf
         ,message_id_8 const& a1){
  try{
    buf.ReserveBytes(4);
    buf.Receive(a1);
    buf.FillInSize(10000);
  }catch(...){buf.Rollback();throw;}
}
}

inline void
cmw_account::MarshalMemberData (::cmw::SendBuffer& buf)const{
  number.Marshal(buf);
  password.Marshal(buf);
}
