#pragma once
// Code generated by the C++ Middleware Writer version 1.14.
#include<SendBuffer.hh>
#include"udp_stuff.hh"
#include<string_plus.hh>

namespace middle_front{
void Marshal (::cmw::SendBuffer& buf
         ,bool a1
         ,cmw::string_plus const& a2={}){
  try{
    buf.ReserveBytes(4);
    buf.Receive(a1);
    if(a1)goto rt;
    a2.Marshal(buf);
rt:
    buf.FillInSize(cmw::udp_packet_max);
  }catch(...){buf.Rollback();throw;}
}
}
