#pragma once
// Code generated by the C++ Middleware Writer version 1.14.
#include<SendBuffer.hh>
#include"udp_stuff.hh"
#include<string_plus.hh>

namespace middle_front{
void Marshal (::cmw::SendBuffer& buf
         ,bool az1
         ,cmw::string_plus const& az2={}){
  try{
    buf.ReserveBytes(4);
    buf.Receive(az1);
    if(az1)goto rt;
    az2.Marshal(buf);
rt:
    buf.FillInSize(cmw::udp_packet_max);
  }catch(...){buf.Rollback();throw;}
}
}
