//File generated by the C++ Middleware Writer version 1.14.
#ifndef cmwA_mdl_hh
#define cmwA_mdl_hh
inline void
cmwCredentials::marshalMembers (auto& buf)const{
  receive(buf,userID);
  password.marshal(buf);
}

struct back{
static void mar (auto& buf
         ,cmwCredentials const& a
         ,::int32_t b){
  a.marshal(buf);
  buf.receive(b);
}

static void mar (auto& buf
         ,cmwRequest const& a){
  a.marshal(buf);
}

template<messageID id,int maxLength=10000>
static void marshal (auto& buf,auto&&...t)try{
  buf.reserveBytes(4);
  buf.template receive<messageID>(id);
  mar(buf,::std::forward<decltype(t)>(t)...);
  buf.fillInSize(maxLength);
}catch(...){buf.rollback();throw;}
};

struct front{
template<int maxLength=10000>
static void marshal (auto& buf
         ,::cmw::stringPlus const& a={}
         ,::int8_t b={})try{
  buf.reserveBytes(4);
  receiveBool(buf,a.size()==0);
  if(a.size()>0){
    receive(buf,a);
    buf.receive(b);
  }
  buf.fillInSize(maxLength);
}catch(...){buf.rollback();throw;}
};
#endif
