//File generated by the C++ Middleware Writer version 1.14.
#ifndef cmwA_mdl_hh
#define cmwA_mdl_hh
inline void
cmwAccount::marshalMembers (::cmw::SendBuffer& buf)const{
  number.marshal(buf);
  password.marshal(buf);
}

struct back{
static ::int32_t mar (auto& buf
         ,::std::vector<cmwAccount> const& a
         ,::int32_t b){
  receiveBlock(buf,a);
  buf.receive(b);
  return 10000;
}

static ::int32_t mar (auto& buf
         ,cmwRequest const& a){
  a.marshal(buf);
  return 700000;
}

template<messageID id,class...T>
static void marshal (::cmw::SendBuffer& buf,T&&...t)try{
  buf.reserveBytes(4);
  buf.receive<messageID>(id);
  buf.fillInSize(mar(buf,::std::forward<T>(t)...));
}catch(...){buf.rollback();throw;}
};

struct front{
template<bool res>
static void marshal (auto& buf
         ,::cmw::stringPlus const& a={}
         ,::int8_t b={})try{
  buf.reserveBytes(4);
  receiveBool(buf,res);
  if(!res){
    receive(buf,a);
    buf.receive(b);
  }
  buf.fillInSize(udpPacketMax);
}catch(...){buf.rollback();throw;}
};
#endif
