//File generated by the C++ Middleware Writer version 1.14.
#ifndef zz_middle_hh
#define zz_middle_hh 1
namespace middle{
void marshal (::cmw::SendBuffer& buf
         ,::cmw::MarshallingInt const& a
         ,char const* b)try{
  buf.reserveBytes(4);
  a.marshal(buf);
  receive(buf,b);
  buf.fillInSize(::cmw::udp_packet_max);
}catch(...){buf.rollback();throw;}
}
#endif
