#ifndef zz_frntMddl_hh
#define zz_frntMddl_hh 1
//Code generated by the C++ Middleware Writer version 1.14.
namespace frntMddl{
void Marshal (::cmw::SendBuffer& buf
         ,::cmw::marshallingInt const& a
         , const char* b)try{
  buf.ReserveBytes(4);
  a.Marshal(buf);
  Receive(buf,b);
  buf.FillInSize(::cmw::udp_packet_max);
}catch(...){buf.Rollback();throw;}
}
#endif
