//File generated by the C++ Middleware Writer version 1.14.
#ifndef zz_mddlBck_hh
#define zz_mddlBck_hh 1
inline void
cmwAccount::marshalMembers (::cmw::SendBuffer& buf)const{
  number.marshal(buf);
  password.marshal(buf);
}

namespace mddlBck{
int32_t Mar (::cmw::SendBuffer& buf
         ,::std::vector<cmwAccount> const& a
         ,::int32_t b){
  receiveGroup(buf,a);
  buf.Receive(b);
  return 10000;
}

int32_t Mar (::cmw::SendBuffer& buf
         ,cmwRequest const& a){
  a.marshal(buf);
  return 700000;
}

int32_t Mar (::cmw::SendBuffer& buf){
  return 10000;
}

template<messageID id,class...T>
void marshal (::cmw::SendBuffer& buf,T&&...t)try{
  buf.reserveBytes(4);
  buf.Receive(static_cast<uint8_t>(id));
  buf.fillInSize(Mar(buf,t...));
}catch(...){buf.rollback();throw;}
}

namespace mddlFrnt{
template<bool res>
void marshal (::cmw::SendBuffer& buf
         ,::cmw::stringPlus const& a={}
         ,::int8_t b={})try{
  buf.reserveBytes(4);
  Receive(buf,res);
  if(!res){
    Receive(buf,a);
    buf.Receive(b);
  }
  buf.fillInSize(udp_packet_max);
}catch(...){buf.rollback();throw;}
}
#endif
