//File generated by the C++ Middleware Writer version 1.14.
#ifndef genz_mdl_h
#define genz_mdl_h
struct middle{
static void marshal (::cmw::SendBuffer& buf
         ,::cmw::MarshallingInt const& a
         ,char const* b)try{
  buf.reserveBytes(4);
  a.marshal(buf);
  receive(buf,b);
  buf.fillInSize(::cmw::udpPacketMax);
}catch(...){buf.rollback();throw;}
};
#endif
