//File generated by the C++ Middleware Writer version 1.15.
#pragma once

struct middle{
template<int maxLength=10000>
static void marshal (auto& buf
         ,::cmw::MarshallingInt const& a
         ,char const* b)try{
  buf.reserveBytes();
  a.marshal(buf);
  receive(buf,b);
  buf.fillInSize(maxLength);
}catch(...){buf.rollback();throw;}
};
